export { default as AboutHero } from './AboutHero';
export { default as HomeBanner } from './HomeBanner';
export { default as HomeBannerSchool } from './HomeBannerSchool';
export { default as HomeHero } from './HomeHero';
export { default as HomeMinimal } from './HomeMinimal';
export { default as HomeDarkMode } from './HomeDarkMode';
export { default as TextLeft } from './TextLeft';
export { default as HomeForDesigner } from './HomeForDesigner';
export { default as HomeColorPresets } from './HomeColorPresets';
export { default as HomePricingPlans } from './HomePricingPlans';
export { default as HomeAdvertisement } from './HomeAdvertisement';
export { default as HomeCleanInterfaces } from './HomeCleanInterfaces';
export { default as HomeHugePackElements } from './HomeHugePackElements';
export { default as TextRight } from './TextRight'
export { default as HomeServiceL02 } from './HomeServiceL02'
export { default as HomeServiceR2 } from './HomeServiceR2'
